conf/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

from conf import settings

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
    }),
    path('admin/', admin.site.urls),
    path('',  include('place.urls')),
]

place/models.py
import re
import json

from django.db import models

def find_links(s):
    #print ('======', s)
    #m = re.search(r'\((.+)\)', s)
    #if m and m.group(1):
    #    print (m.group(1))
    # TODO recursive find pattern
    links = []
    if '),(' in s:
        slist = s.split('),(')
        for i in slist:
            p = i.replace(')', '').replace('(', '')
            if ',' in p:
                q = p.split(',')
                links.append('<a href={} target="_blank" class="text is-link">{}</a>'.format(q[1], q[0]))
            else:
                links.append(p)
    else:
        p = s.replace(')', '').replace('(', '')
        if ',' in p:
            q = p.split(',')
            links.append('<a href={} target=_"blank" class="text is-link">{}</a>'.format(q[1], q[0]))
        else:
            links.append(p)

    return ', '.join(links)


class Species(models.Model):
    scientific_name = models.CharField(max_length=500)
    name_code = models.CharField(max_length=500)
    vernacular_name = models.CharField(max_length=500)
    description = models.TextField(default='', blank=True)
    locality = models.TextField(default='', blank=True)
    image_list = models.TextField(default='', blank=True)

    def __str__(self):
        return '<Species {}>'.format(self.vernacular_name)

    def get_images(self):
        if self.image_list:
            return json.loads(self.image_list)

    @property
    def description_cleaned(self):
        return self.description.replace('<p>', '').replace('</p>', '')

    @property
    def locality_cleaned(self):
        return self.locality.replace('<p>', '').replace('</p>', '')

    class Meta:
        ordering = ['-image_list']

class InfoText(models.Model):
    name = models.CharField(max_length=500)
    content = models.TextField(blank=True, null=True)

    def __str__(self):
        return '<InfoText({}) {}>'.format(self.id, self.name)


class Link(models.Model):
    CAT_CHOICES = [
        ('rule', '相關規範'),
        ('admin', '所有權/管理單位'),
        ('sponsor', '認養單位'),
        ('contact', '諮詢對象-民間/公部門'),
        ('nursery', '苗圃'),
        ('garden', '植物園與環教場所'),
        ('case', '參考綠化案例'),
    ]

    title = models.CharField(max_length=500)
    url = models.URLField()
    category = models.CharField(max_length=32, choices=CAT_CHOICES)


class Place(models.Model):
    ACTION_CHOICES = [
        ('vision', '【願景蒐集型】'),
        ('adopt', '【代管認養型】我要認養'),
        ('donate-gov', '【捐款型】支認公部門綠化業務'),
        ('donate-ngo', '【捐款型】支持民間認養單位'),
        ('environ', '【環境復育型】'),
    ]
    source_id = models.IntegerField(blank=True, null=True)
    county = models.CharField(blank=True, null=True, max_length=500)
    title = models.CharField(max_length=500)
    description = models.TextField(blank=True, null=True)
    place_type = models.CharField('用地類型', blank=True, null=True, max_length=500)
    action_type = models.CharField('推動形式', blank=True, null=True, max_length=500, choices=ACTION_CHOICES)

    rule_text = models.TextField('相關規範', blank=True)
    owner_text = models.TextField('所有權單位', blank=True)
    administrator_text = models.TextField('管理單位', blank=True)
    contact_text = models.TextField('諮詢對象-民間/公部門', blank=True)
    sponsor_text = models.TextField('認養單位', blank=True) # some place has value, error! need clean
    nursery_text = models.TextField('苗圃', blank=True)
    garden_text = models.TextField('植物園與環教場所', blank=True)
    case_text = models.TextField('參考綠化案例', blank=True)

    #contact = models.ForeignKey(Link, on_delete=models.SET_NULL, null=True, blank=True, limit_choices_to={'category':'contact'}, related_name='contact_places')
    #owner = models.ForeignKey(Link, on_delete=models.SET_NULL, null=True, blank=True, limit_choices_to={'category':'admin'}, related_name='owner_places')
    #administrator = models.ForeignKey(Link, on_delete=models.SET_NULL, null=True, blank=True, limit_choices_to={'category':'admin'}, related_name='admin_places')
    #sponsor = models.ForeignKey(Link, on_delete=models.SET_NULL, null=True, blank=True, limit_choices_to={'category': 'sponsor'}, related_name='sponsor_places')
    link = models.URLField('相簿與討論區', blank=True, null=True)
    cover_url= models.TextField(blank=True, null=True) # only fit 200 chars
    lat = models.CharField(blank=True, null=True, max_length=500)
    lon = models.CharField(blank=True, null=True, max_length=500)
    #x97 = models.TextField(blank=True, null=True)
    #y97 = models.TextField(blank=True, null=True)
    #tree_info = models.TextField(blank=True, null=True)
    #check_info = models.TextField(blank=True, null=True)
    species_list = models.ManyToManyField(Species, related_name='places', blank=True)

    #land_script_url_list
    #filter = models.TextField(blank=True, null=True)
    #desc_long = models.TextField(blank=True, null=True)
    #desc_detailed = models.TextField(blank=True, null=True)
    #button_label = models.TextField(blank=True, null=True)
    #is_multi = models.TextField(blank=True, null=True)
    #shape_area = models.TextField(blank=True, null=True)
    #size_available = models.TextField(blank=True, null=True)
    #replant_size = models.TextField(blank=True, null=True)
    #revised_replant_size = models.TextField(blank=True, null=True)

    def __str__(self):
        return '<Place {}-{}>'.format(self.county, self.title)

    def get_rule_links(self):
        if not self.rule_text:
            return ''

        return find_links(self.rule_text)

    def get_owner_links(self):
        if not self.owner_text:
            return ''

        return find_links(self.owner_text)

    def get_administrator_links(self):
        if not self.administrator_text:
            return ''

        return find_links(self.administrator_text)


    def get_nursery_links(self):
        if not self.nursery_text:
            return ''

        return find_links(self.nursery_text)

    def get_sponsor_links(self):
        if not self.sponsor_text:
            return ''

        return find_links(self.sponsor_text)

    def get_contact_links(self):
        if not self.contact_text:
            return ''

        return find_links(self.contact_text)

    def get_garden_links(self):
        if not self.garden_text:
            return ''

        return find_links(self.garden_text)

    def get_case_links(self):
        if not self.case_text:
            return ''

        return find_links(self.case_text)

    @property
    def tree_species_info(self):
        if info := InfoText.objects.get(pk=1):
            return info.content

    @property
    def checklist_info(self):
        if info := InfoText.objects.get(pk=2):
            return info.content


def get_image_path(instance, filename):
    #print (instance, filename, instance.collection, instance.pk)
    #print (instance.CAT, instance)
    if instance.pk:
        place_id = instance.place_id
        ext = filename.split('.')[-1].lower()
        path = 'place/{}/{}/{}.{}'.format(place_id, instance.CAT, instance.pk, ext)
        #exist_path = os.path.join(settings.MEDIA_ROOT, path)
        return path
    return ''


class RelatedImage(models.Model):
    image = models.ImageField(upload_to=get_image_path, blank=True)
    url= models.URLField(blank=True, null=True)
    position = models.PositiveSmallIntegerField(default=0)

    def save(self, *args, **kwargs):
        if self.pk is None:
            saved_image = self.image
            self.image = None
            super(RelatedImage, self).save(*args, **kwargs)
            self.image = saved_image

        super(RelatedImage, self).save(*args, **kwargs)

        class Meta:
            abstract = True

class LandScriptImage(RelatedImage):
    CAT = 'land_script'

    place = models.ForeignKey(Place, related_name='land_script_images', on_delete=models.SET_NULL, null=True)

class UnlimitedCitiesImage(RelatedImage):
    CAT = 'unlimited_cities'

    place = models.ForeignKey(Place, related_name='unlimited_cities_images', on_delete=models.SET_NULL, null=True)

templates/layout.html
{% load utils %}
<!DOCTYPE html>
<html>
<head>
  <title>tree-patching::{{ item.county }}::{{ item.title }}</title>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="/static/css/musubii.min.css" />
  <link rel="stylesheet" href="/static/css/place.css" />
  <!--link rel="stylesheet" href="/static/css/github-markdown.min.css"-->
  <!--link href="/static/css/markdown.css" rel="stylesheet"></link-->
  <style>
    .markdown-body {
        box-sizing: border-box;
        min-width: 200px;
        max-width: 980px;
        margin: 0 auto;
        padding: 45px;
    }

    @media (max-width: 767px) {
        .markdown-body {
            padding: 15px;
        }
    }

    .markdown-body h1,
    .markdown-body h2,
    .markdown-body h3,
    .markdown-body h4,
    .markdown-body h5,
    .markdown-body h6 {
  font-weight: normal;
  color: #111;
  line-height: 1em;
}
    .markdown-body h4,
    .markdown-body h5,
    .markdown-body h6 {
        font-weight: bold;
    }

.markdown-body h1 {
  font-size: 2.5em;
}

.markdown-body h2 {
  font-size: 2em;
}

.markdown-body h3 {
  font-size: 1.5em;
}

.markdown-body h4 {
  font-size: 1.2em;
}

.markdown-body h5 {
  font-size: 1em;
}

.markdown-body h6 {
  font-size: 0.9em;
}

.markdown-body blockquote {
  color: #666666;
  margin: 0;
  padding-left: 3em;
  border-left: 0.5em #eee solid;
}
.markdown-body ul,
.markdown-body ol {
  margin: 1em 0;
  padding: 0 0 0 2em;
  list-style: unset;
}

.markdown-body ol {
    list-style: decimal;
}
.markdown-body li p:last-child {
  margin: 0;
}

  </style>
  <script>
    function initMap() {
      var fenway = {lat: 42.345573, lng: -71.098326};
      var map = new google.maps.Map(document.getElementById('map'), {
        center: fenway,
        zoom: 14
      });
      var panorama = new google.maps.StreetViewPanorama(
        document.getElementById('pano'), {
          position: fenway,
          pov: {
            heading: 34,
            pitch: 10
          }
        });
      map.setStreetView(panorama);
    }
    /*
    var panorama = new google.maps.StreetViewPanorama(
      document.getElementById('pano'), {
        position: {lat: 37.869260, lng: -122.254811},
        pov: {heading: 165, pitch: 0},
        motionTracking: false
      });
*/
  </script>
  <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBgkoBw0w-Q3A-QQOIcPt-xhiz9ae2XDWM&callback=initMap" type="text/javascript"></script>
</head>
<body>
  <div class="app">
    <header class="section is-header is-padding-top-safe">
      <div class="inner is-padding-right-sm is-padding-left-md">
	<div class="grid is-middle is-between">
	  <div class="column">
	    <div class="box is-flex is-bottom">
	      <div class="box is-margin-right-sm">
                <span class="tree-logo"><a href="https://bit.ly/tree-taiwan-sites">台灣好植地 Patch by Planting</a></span>
	      </div>
	      <div class="box is-flex">
		<span class="text is-font-sans-en is-line-height-xs is-xs"></span>
	      </div>
	    </div>
	  </div>
	</div>
      </div>
    </header>
    <main>
      <div id="map"></div>
      <section class="section is-hero is-padding-horizontal-safe is-wide-lg">
	<div class="inner is-padding-horizontal-md">
	  <div class="grid is-middle is-center is-gap-xxl">
	    <div class="column is-space-md">
	      <p class="text is-primary is-font-sans-en is-weight-700">
		<span class="text is-block is-hero-1 tree-title">{{ item.county }} - {{ item.title }}</span>
	      </p>
	      <h1 class="text is-line-height-lg is-sm">
		<span class="text is-fablet-block">{{ item.description }}</span>
	      </h1>
	    </div>
	  </div>
	</div>
      </section>
      <section class="section is-hero is-padding-horizontal-safe is-wide-lg">
	<div class="inner is-padding-horizontal-md">
	  <h2 class="tree-subtitle">基本資料</h2>
	  <div class="grid is-center is-top is-gap-md">
	    <div class="column is-6">
	      <div><img src="{{ item.cover_url }}"></div>
	    </div>
	    <div class="column is-6">
	      <div class="card is-radius-sm is-bg-light is-floating">
		<div class="box is-padding-md">
		  <ul class="list is-disc">
		    <li class="item">用地類型：{{ item.place_type }}</li>
		    <li class="item">推動形式：{{ item.get_action_type_display }}</li>
		    <li class="item">相關規範：{{ item.get_rule_links|safe }}</li>
		    <li class="item">所有權單位：{{ item.get_owner_links|safe }}</li>
		    <li class="item">管理單位：{{ item.get_administrator_links|safe }}</li>

                    <li class="item">諮詢對象-民間/公部門：{{ item.get_contact_links|safe }}</li>

		    <li class="item">認養單位：{{ item.get_sponsor_links|safe }}</li>
                    <li class="item">苗圃：{{ item.get_nursery_links|safe }}</li>
                    <li class="item">參考綠化案例：{{ item.get_case_links|safe }}</li>
		    <li class="item">植物園與環教場所：{{ item.get_garden_links|safe }}</li>
                    <li class="item">相簿與討論區：<a href="{{ item.link }}" target="_blank" class="text is-link is-info">連結</a></li>
		    <li class="item">經緯度：{% if item.lon and item.lat %}{{ item.lon}}, {{ item.lat }} <a href="https://www.google.com.tw/maps/@{{ item.lat }},{{ item.lon}},1171m/data=!3m1!1e3?hl=zh-TW" target="_blank" class="text is-link">google地圖</a>{% endif%}</li>
		  </ul>
		</div>
	      </div>
	    </div>
	  </div>
	</div>
      </section>
      <section class="section is-hero is-padding-horizontal-safe is-wide-lg">
        <div class="inner is-padding-horizontal-md">
	  <h2 class="tree-subtitle">分析與工具</h2>
	  <div class="grid is-center is-top is-gap-md">
	    <div class="column is-12">
              <h4 class="tree-subtitle2">樹種資料應用</h4>
              <div class="card is-radius-sm is-bg-light is-floating">
                <div class="markdown-body">{{ item.tree_species_info | markdown | safe }}</div>
              </div>
            </div>
          </div>
	  <div class="grid is-top is-gap-md is-margin-sm">
            {% for i in item.species_list.all %}
            <div class="column is-12">
              <span class="badge is-plain">{{ i.vernacular_name }}</span>
              <div><small>{{ i.scientific_name }}</small></div>
              <div class="is-card"><small>描述: {{ i.description_cleaned }}<br>
                  分佈: {{ i.locality_cleaned }}
              </small></div>
            </div>

            {% for j in i.get_images %}
            <div class="column is-3">
              <img src="{{ j.image_big}}">
            </div>
            {% endfor %}
            {% endfor %}            
            {% comment %}
            {% for i in item.species_list.all %}
	    <div class="column is-4">
              {% if i.get_images|length %}<img src="{{ i.get_images.0.image_big}}">{% endif %}
              <span class="badge is-plain">{{ i.vernacular_name }}</span>
              <div><small>{{ i.scientific_name }}</small></div>
              <hr>
              <div class="is-card"><small>描述: {{ i.description_cleaned }}</small></div>
              <div class="is-card"><small>分佈: {{ i.locality_cleaned }}</small></div>
            </div>
            {% endfor %}
            {% endcomment %}
          </div>
          {% if item.species_list.count %}
          <div class="grid is-center is-top is-gap-md is-margin-sm">
	    <div class="column is-12"><div>資料來源: <a href="https://taicol.tw" target="_blank" class="text is-link is-primary">台灣物種名錄 TaiCoL</a> |  <a href="https://taieol.tw" target="_blank" class="text is-link is-primary">台灣生命大百科</a></div>
            </div>
          </div>
          {% endif %}
	  <h2 class="tree-subtitle">Land Script 分析初評</h2>
	  <div class="grid is-center is-top is-gap-md">
	    <div class="column is-12">
              <small>Powered by <a href="https://hackmd.io/-93qFuokQKOpPLEJKL4yaA" class="text is-link is-primary" target="_blank">LandScript</a></small>
            </div>
            {% for i in item.land_script_images.all %}
            <div class="column is-6">
              <img src="{% if i.image %}{{ i.image.url }}{% elif i.url %}{{ i.url }}{% endif %}">
            </div>
            {% endfor %}
          </div>

	  <h2 class="tree-subtitle">Unlimited Cities DIY 願景方案</h2>
	  <div class="grid is-center is-top is-gap-md">
	    <div class="column is-12">
              <small>Powered by <a href="https://www.host-lab.org/" class="text is-link is-primary" target="_blank">HOST Lab</a></small>
            </div>
            {% for i in item.unlimited_cities_images.all %}
            <div class="column is-6">
              <img src="{% if i.image %}{{ i.image.url }}{% elif i.url %}{{ i.url }}{% endif %}">
            </div>
            {% endfor %}
          </div>
          <div class="column is-12">
            <a href="https://bit.ly/Unlimited-Cities-DIY-demo" target="_blank" class="text is-link is-primary">運用網頁工具，繪製您的願景方案</a>
          </div>
        </div>
        <div class="inner is-padding-horizontal-md">
	  <h2 class="tree-subtitle">建議查核項目</h2>
	  <div class="grid is-center is-top is-gap-md">
	    <div class="column is-12">
              <div class="card is-radius-sm is-bg-light is-floating">
                <div class="markdown-body">{{ item.checklist_info | markdown | safe }}</div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </main>
  </div>
  <script>
    (function(exports) {
      "use strict";

      function initMap() {
        console.log('init map');
        exports.map = new google.maps.Map(document.getElementById("map"), {
          center: {
            lat: -34.397,
            lng: 150.644
          },
          zoom: 8
        });
      }
      console.log('-----')
      exports.initMap = initMap;
    })((this.window = this.window || {}));
  </script>
  <script>
    const mdLinks = document.querySelectorAll('.markdown-body a');
    for (let i in mdLinks) {
      mdLinks[i].className = 'text is-link';
      mdLinks[i].target = '_blank';
    }
  </script>  
</body>
</html>